/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SystemRouteImport } from './routes/system'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts/$accountId'
import { Route as PersonsIndexRouteImport } from './routes/persons/index'
import { Route as PersonsPersonIdRouteImport } from './routes/persons/$personId'
import { Route as AccountsAccountIdIndexRouteImport } from './routes/accounts/$accountId/index'
import { Route as AccountsAccountIdChatsRouteImport } from './routes/accounts/$accountId/chats'
import { Route as AccountsAccountIdContactsRouteImport } from './routes/accounts/$accountId/contacts'
import { Route as AccountsAccountIdRequestsRouteImport } from './routes/accounts/$accountId/requests'
import { Route as AccountsAccountIdChatsIndexRouteImport } from './routes/accounts/$accountId/chats/index'
import { Route as AccountsAccountIdChatsChatIdRouteImport } from './routes/accounts/$accountId/chats/$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/persons/$personId',
  path: '/persons/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdIndexRoute = AccountsAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsAccountIdRoute,
} as any)
const AccountsAccountIdChatsRoute = AccountsAccountIdChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AccountsAccountIdRoute,
} as any)
const AccountsAccountIdContactsRoute =
  AccountsAccountIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)
const AccountsAccountIdRequestsRoute =
  AccountsAccountIdRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)
const AccountsAccountIdChatsIndexRoute =
  AccountsAccountIdChatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountsAccountIdChatsRoute,
  } as any)
const AccountsAccountIdChatsChatIdRoute =
  AccountsAccountIdChatsChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => AccountsAccountIdChatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/requests': typeof RequestsRoute
  '/system': typeof SystemRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/accounts/$accountId/chats': typeof AccountsAccountIdChatsRouteWithChildren
  '/accounts/$accountId/contacts': typeof AccountsAccountIdContactsRoute
  '/accounts/$accountId/requests': typeof AccountsAccountIdRequestsRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/accounts/$accountId/chats/$chatId': typeof AccountsAccountIdChatsChatIdRoute
  '/accounts/$accountId/chats/': typeof AccountsAccountIdChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/requests': typeof RequestsRoute
  '/system': typeof SystemRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/persons': typeof PersonsIndexRoute
  '/accounts/$accountId/contacts': typeof AccountsAccountIdContactsRoute
  '/accounts/$accountId/requests': typeof AccountsAccountIdRequestsRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
  '/accounts/$accountId/chats/$chatId': typeof AccountsAccountIdChatsChatIdRoute
  '/accounts/$accountId/chats': typeof AccountsAccountIdChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/requests': typeof RequestsRoute
  '/system': typeof SystemRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/accounts/$accountId/chats': typeof AccountsAccountIdChatsRouteWithChildren
  '/accounts/$accountId/contacts': typeof AccountsAccountIdContactsRoute
  '/accounts/$accountId/requests': typeof AccountsAccountIdRequestsRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/accounts/$accountId/chats/$chatId': typeof AccountsAccountIdChatsChatIdRoute
  '/accounts/$accountId/chats/': typeof AccountsAccountIdChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/requests'
    | '/system'
    | '/accounts/$accountId'
    | '/persons/$personId'
    | '/accounts/'
    | '/persons/'
    | '/accounts/$accountId/chats'
    | '/accounts/$accountId/contacts'
    | '/accounts/$accountId/requests'
    | '/accounts/$accountId/'
    | '/accounts/$accountId/chats/$chatId'
    | '/accounts/$accountId/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/requests'
    | '/system'
    | '/persons/$personId'
    | '/accounts'
    | '/persons'
    | '/accounts/$accountId/contacts'
    | '/accounts/$accountId/requests'
    | '/accounts/$accountId'
    | '/accounts/$accountId/chats/$chatId'
    | '/accounts/$accountId/chats'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/requests'
    | '/system'
    | '/accounts/$accountId'
    | '/persons/$personId'
    | '/accounts/'
    | '/persons/'
    | '/accounts/$accountId/chats'
    | '/accounts/$accountId/contacts'
    | '/accounts/$accountId/requests'
    | '/accounts/$accountId/'
    | '/accounts/$accountId/chats/$chatId'
    | '/accounts/$accountId/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  RequestsRoute: typeof RequestsRoute
  SystemRoute: typeof SystemRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRouteWithChildren
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/persons'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/': {
      id: '/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AccountsAccountIdIndexRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/chats': {
      id: '/accounts/$accountId/chats'
      path: '/chats'
      fullPath: '/accounts/$accountId/chats'
      preLoaderRoute: typeof AccountsAccountIdChatsRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/contacts': {
      id: '/accounts/$accountId/contacts'
      path: '/contacts'
      fullPath: '/accounts/$accountId/contacts'
      preLoaderRoute: typeof AccountsAccountIdContactsRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/requests': {
      id: '/accounts/$accountId/requests'
      path: '/requests'
      fullPath: '/accounts/$accountId/requests'
      preLoaderRoute: typeof AccountsAccountIdRequestsRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/chats/': {
      id: '/accounts/$accountId/chats/'
      path: '/'
      fullPath: '/accounts/$accountId/chats/'
      preLoaderRoute: typeof AccountsAccountIdChatsIndexRouteImport
      parentRoute: typeof AccountsAccountIdChatsRoute
    }
    '/accounts/$accountId/chats/$chatId': {
      id: '/accounts/$accountId/chats/$chatId'
      path: '/$chatId'
      fullPath: '/accounts/$accountId/chats/$chatId'
      preLoaderRoute: typeof AccountsAccountIdChatsChatIdRouteImport
      parentRoute: typeof AccountsAccountIdChatsRoute
    }
  }
}

interface AccountsAccountIdChatsRouteChildren {
  AccountsAccountIdChatsChatIdRoute: typeof AccountsAccountIdChatsChatIdRoute
  AccountsAccountIdChatsIndexRoute: typeof AccountsAccountIdChatsIndexRoute
}

const AccountsAccountIdChatsRouteChildren: AccountsAccountIdChatsRouteChildren =
  {
    AccountsAccountIdChatsChatIdRoute: AccountsAccountIdChatsChatIdRoute,
    AccountsAccountIdChatsIndexRoute: AccountsAccountIdChatsIndexRoute,
  }

const AccountsAccountIdChatsRouteWithChildren =
  AccountsAccountIdChatsRoute._addFileChildren(
    AccountsAccountIdChatsRouteChildren,
  )

interface AccountsAccountIdRouteChildren {
  AccountsAccountIdChatsRoute: typeof AccountsAccountIdChatsRouteWithChildren
  AccountsAccountIdContactsRoute: typeof AccountsAccountIdContactsRoute
  AccountsAccountIdRequestsRoute: typeof AccountsAccountIdRequestsRoute
  AccountsAccountIdIndexRoute: typeof AccountsAccountIdIndexRoute
}

const AccountsAccountIdRouteChildren: AccountsAccountIdRouteChildren = {
  AccountsAccountIdChatsRoute: AccountsAccountIdChatsRouteWithChildren,
  AccountsAccountIdContactsRoute: AccountsAccountIdContactsRoute,
  AccountsAccountIdRequestsRoute: AccountsAccountIdRequestsRoute,
  AccountsAccountIdIndexRoute: AccountsAccountIdIndexRoute,
}

const AccountsAccountIdRouteWithChildren =
  AccountsAccountIdRoute._addFileChildren(AccountsAccountIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  RequestsRoute: RequestsRoute,
  SystemRoute: SystemRoute,
  AccountsAccountIdRoute: AccountsAccountIdRouteWithChildren,
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  PersonsIndexRoute: PersonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
